apiVersion: v1
kind: Service
metadata:
  name: service-api-converter
  labels:
    name: lbl-api-converter
spec:
  selector:
    name: lbl-api-converter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

